data_ingestion:
  bucket_name: "anime_project"
  bucket_file_names:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

  
  model:
    embedding_size:  128
    loss: binary_crosssentropy
    optimizer: Adam
    metrics: ["mae", "mse"]
    

    
    